# NumPy Practice Notebook

In [34]:
import numpy as np

## 1: Array Basics

In [35]:
my_list = [x * 10 for x in range(1, 11)]

my_array = np.array(my_list)

my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [36]:
my_array.ndim

1

In [37]:
my_array.shape

(10,)

In [38]:
my_array.size

10

In [39]:
my_array.dtype

dtype('int64')

## 2: Array Creation and RNG

In [40]:
my_array = np.linspace(10, 100, 10, dtype=int).reshape(5, 2)

my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [41]:
rng = np.random.default_rng(2022)

random_array = rng.random(9).reshape(3, 3)

random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

## 3: Accessing Array Data

In [42]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [43]:
random_array[:, :1]

array([[0.24742606],
       [0.06066207],
       [0.1108689 ]])

In [44]:
random_array[2, 1]

np.float64(0.04305584439252108)

## 4: Arithmetic Operations

In [45]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [46]:
rng = np.random.default_rng(2022)

discount_pct = rng.random(6)

discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [47]:
pct_owed = 1 - discount_pct

pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [48]:
final_owed = total * pct_owed

final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

## 5: Filtering Arrays

In [49]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products[prices > 25]

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [50]:
#I got a little confused here, thinking I need np.array syntax to create the array.
#Turns out the reference to the other arrays was sufficient in creating a new array.

#Creating a filter variable would have been cleaner, but this is still correct.

fancy_feast_special = products[(prices > 25) | (products == "cola")]

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [51]:
shipping_cost = np.where(prices > 20, 0, 5)

shipping_cost

array([5, 5, 0, 0, 5, 0])

## 6: Aggregating and Sorting

In [52]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices_top = np.sort(prices)[3:6]

prices_top

array([22.49, 49.99, 99.99])

In [53]:
#Could have used print(f"Mean: {}") etc. to make it look more presentable

prices_top_mean = prices_top.mean()

prices_top_min = prices_top[0]

prices_top_max = prices_top[2]

prices_top_median = prices_top[1]

prices_top_mean, prices_top_min, prices_top_max, prices_top_median

(np.float64(57.49), np.float64(22.49), np.float64(99.99), np.float64(49.99))

In [56]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

len(np.unique(price_tiers))

3

## 7: Recapping What I've Learned

Task:
To filter an array, take a random sample from that new array, then use .where to categorise the data into a final array (by mean and median).

In [2]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "path_to_dataset", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [115]:
mask = (family_array == "PRODUCE")

produce_array = sales_array[mask]

In [116]:
rng = np.random.default_rng(2022)

random_array = rng.random(30)

sampled_array = produce_array[random_array < 0.5]

In [117]:
mean = sampled_array.mean()

median = np.median(sampled_array)

print(f"Mean: {sampled_array.mean()}")

print(f"Median: {np.median(sampled_array)}")

Mean: 2268.102470588235
Median: 1272.755


In [120]:
#My mistake here was I wrote a > instead of a >=, leaving the actual median case uncategorised.

final_array = np.where((sampled_array > mean) & (sampled_array > median),
                       "above_both",
                       np.where((sampled_array >= median), "above_median", "below_both"))

final_array

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')